from tkinter import *
tk=Tk()
Ankara = Label(text="Ankara")
Ankara.grid(row=0,column=0)
İstanbul = Label(text="İstanbul")
İstanbul.grid(row=1,column=0)
İzmir = Label(text="İzmir")
İzmir.grid(row=2,column=0)
ankara_g = Entry()
ankara_g.grid(row=0,column=1)
istanbul_g = Entry()
istanbul_g.grid(row=1,column=1)
izmir_g = Entry()
izmir_g.grid(row=2,column=1)
mainloop()
